version: 0.0.0.{build}

environment:
  packageVersion: 0.0.0

init:
- ps: $env:buildVersion = "$env:packageVersion.$env:appveyor_build_number"
- ps: $env:nugetVersion = "$env:packageVersion-beta-$env:appveyor_build_number"
- ps: Update-AppveyorBuild -Version $env:buildVersion

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(buildVersion)'
  assembly_file_version: '$(buildVersion)'
  assembly_informational_version: '$(nugetVersion)'

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

configuration: Release

nuget:
  account_feed: true
  disable_publish_on_pr: true

cache:
- packages -> **\packages.config

before_build:
- nuget restore ./src/DataDog.Api.sln

build:
  project: ./src/DataDog.Api.sln
  publish_nuget: true
  verbosity: minimal

deploy:
  provider: NuGet
  api_key:
    secure: 2K5EQwNNYpt5GMRVKxHTihZO2MZCUSbsngmYo63XPO73UoX0n7INS/4OGIrZ3mMe
  artifact: /.*\.nupkg/
  on:
    branch: release
