version: 0.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

configuration: Release

nuget:
  account_feed: true
  disable_publish_on_pr: true

cache:
- packages -> **\packages.config

before_build:
- cmd: nuget.exe restore ./src/DataDog.Api.sln

build:
  project: ./src/DataDog.Api.sln
  publish_nuget: true
  verbosity: minimal

deploy:
  provider: NuGet
  api_key:
    secure: 2K5EQwNNYpt5GMRVKxHTihZO2MZCUSbsngmYo63XPO73UoX0n7INS/4OGIrZ3mMe
  artifact: /.*\.nupkg/
